# Generated by Django 5.0.7 on 2025-05-16 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_alter_allbooks_user_alter_book_all_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('is_profile_public', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Currently Reading', 'Currently Reading'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Currently Reading', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='bookapp.user')),
                ('total_books_read', models.PositiveIntegerField(default=0)),
                ('total_pages_read', models.PositiveIntegerField(default=0)),
                ('avg_pages_per_day', models.FloatField(default=0.0)),
                ('most_read_genre', models.CharField(blank=True, max_length=100)),
                ('current_streak', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookapp.user'),
        ),
        migrations.CreateModel(
            name='ReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=10)),
                ('target_pages', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_goals', to='bookapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pages_read', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bookapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='bookapp.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='all_books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_pages',
        ),
        migrations.CreateModel(
            name='CalendarHeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pages_read', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='bookapp.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='AllBooks',
        ),
    ]
